from = node v24.17.0.

workdir = /app

copy = package*.json ./

run = npm install

copy = . .

expose = 3001

cmd = [node, --watch, app.js]

# Build with: docker build -t <name of tag> .
# the point do not forget the point it is an important point to remember
